### ISSUE TITLE
Error when getting dashboard with v1 API

### ISSUE THREAD

**Issue by LumixximuL** [DataDog/datadog-api-client-typescript#423]
**Describe the bug**
Getting an error when calling to get a dashboard using `new v1.DashboardsApi(config).getDashboard({dashboardId})`

```
Error: missing required property 'definition'
    at Function.ObjectSerializer.deserialize (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/models/ObjectSerializer.js:1713:27)
    at Function.ObjectSerializer.deserialize (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/models/ObjectSerializer.js:1657:55)
    at Function.ObjectSerializer.deserialize (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/models/ObjectSerializer.js:1708:60)
    at DashboardsApiResponseProcessor.<anonymous> (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/apis/DashboardsApi.js:639:38)
    at step (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/apis/DashboardsApi.js:46:23)
    at Object.next (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/apis/DashboardsApi.js:27:53)
    at fulfilled (/Users/taylorwebber/Projects/slackcat/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/apis/DashboardsApi.js:18:58)
```

I believe it is a validation error related to the definition within the widgets array on the dashboard.

When I go to the dashboard and export the JSON manually or use curl to pull the data, the JSON is returned successfully and all the widgets returned have a definition property

**To Reproduce**
1. Use `v1.0.0-beta.6` of library
2. Call to get dashboard
3. Error thrown on request

**Expected behavior**
Return JSON of dashboard

**Environment and Versions (please complete the following information):**
Using version `1.0.0-beta.6` of @datadog/datadog-api-client

**Comment by therve** [comment]
Thanks for your report. Can you give some detail about the dashboard you're trying to fetch? We must have some issues with some particular widgets.

**Comment by LumixximuL** [comment]
@therve I think it is the free space space line graph that we have. The odd thing again is that, the definition does exist when exporting the JSON or using curl.

Let me know what other info you may need.

<img width="478" alt="Screen Shot 2021-12-14 at 7 14 52 AM" src="https://user-images.githubusercontent.com/6784596/146005190-6f24c7a0-d2fb-4e71-8208-f9e2cfdd3649.png">

**Comment by therve** [comment]
It's to be expected that the definition exists in curl, it's just that the typescript client fails to parse the payload for some reason. Can you give me the dashboard name if it's not too sensitive? Otherwise contact support to communicate the dashboard ID? Thanks.

**Comment by LumixximuL** [comment]
@therve the name of our dashboard is "Wisdom"

**Comment by therve** [comment]
It's weird, it seems to be a standard timeseries widget. I copied that dashboard json and imported fine in another org, no idea what's going on.

**Comment by LumixximuL** [comment]
With the same beta version of the library we are using? 🤔

**Comment by therve** [comment]
Right using the latest release.

**Comment by therve** [comment]
Can you try the git version with `debug` flag set? Maybe it'll give us more information.

**Comment by therve** [comment]
Please try with the latest release. Feel free to reopen if it's still happening. Thanks.
