### ISSUE TITLE
Intermittent error querying metrics

### ISSUE THREAD

**Issue by TimCorwinCytiva** [DataDog/datadog-api-client-typescript#832]
**Describe the bug**
When calling v1.MetricsApi.queryMetrics() for 5 metrics over the last 5 minutes, most of the time I get a normal response, with the metric timeseries values if any.

However, for 30min-several hour windows, I instead get an exception:
Error: missing required property 'errors'
    at Function.Object.<anonymous>.ObjectSerializer.deserialize (C:\git\edge-management\node_src\node_modules\@datadog\datadog-api-client\packages\datadog-api-client-v1\models\ObjectSerializer.ts:2178:17)
    at MetricsApiResponseProcessor.<anonymous> (C:\git\edge-management\node_src\node_modules\@datadog\datadog-api-client\packages\datadog-api-client-v1\apis\MetricsApi.ts:621:38)
    at step (C:\git\edge-management\node_src\node_modules\@datadog\datadog-api-client\dist\packages\datadog-api-client-v1\apis\MetricsApi.js:48:23)
    at Object.next (C:\git\edge-management\node_src\node_modules\@datadog\datadog-api-client\dist\packages\datadog-api-client-v1\apis\MetricsApi.js:29:53)
    at fulfilled (C:\git\edge-management\node_src\node_modules\@datadog\datadog-api-client\dist\packages\datadog-api-client-v1\apis\MetricsApi.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
	

**To Reproduce**

Call  v1.MetricsApi.queryMetrics() with valid credentials and params.
Usually I will get a response like: 
![image](https://user-images.githubusercontent.com/91975775/189146671-d53ce23f-8fd5-4b0c-893f-60972c19920f.png)

however, during some windows I just get the Exception above, rather than any MetricsQueryResponse at all.
Nothing changes in the query params other than the fromData and toDate being calculated from the current time.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
I have reproduced the issue with 1.1.0 and 1.3.0, against the 'cytiva' organization.

**Comment by TimCorwinCytiva** [comment]
More testing when I got another window, using Postman suggests this might be a throttling issue, being mishandled by the client?
![image](https://user-images.githubusercontent.com/91975775/189180284-5bc633e7-6e3f-4c42-b728-ec00f71b9b96.png)

**Comment by therve** [comment]
Hi,

The 429 error is legit, #836 should fix the issue where the error doesn't bubble up properly. Thanks.
