### ISSUE TITLE
Log Aggregate API doesn't support Integer facets on group_by expression

### ISSUE THREAD

**Issue by genixpro** [DataDog/datadog-api-client-typescript#922]
**Describe the bug**
The API client is erroring out when attempting to do a group_by facet on an Integer. It appears the API from Datadog is returning the right result, but the API client is parsing it wrong and producing an error.

**To Reproduce**
1) Have your service output JSON logs that contain a number field.
2) Create a facet on that number field with the type "Integer".
3) Make an API call to the logs aggregation endpoint, with a group_by set with that integer field as the facet.

I then get the following error: /Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1550
                throw new TypeError(`unknown type '${type}'`);
                      ^

TypeError: unknown type 'string'
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1550:23)
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1518:57)
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1556:60)
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1498:55)
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1556:60)
    at ObjectSerializer.deserialize (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/models/ObjectSerializer.js:1556:60)
    at LogsApiResponseProcessor.<anonymous> (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/apis/LogsApi.js:177:66)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bradley/slash2/common/temp/node_modules/.pnpm/@datadog+datadog-api-client@1.6.0/node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v2/apis/LogsApi.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

After tracing several of the internals of the library at the lines given in the stacktrace, I determined that the code is attempting to parse an integer as if it were a string.

Specifically, the condition on this code is failing:
        else if (primitives.includes(type.toLowerCase()) &&
            typeof data == type.toLowerCase()) {
            return data;
        }

Because `typeof data` is "number", but `type` is "string", it simply fails to parse this result.

**Expected behavior**
Code returns the faceted aggregate results, the same way the UI does.

**Environment and Versions (please complete the following information):**

API client is version 1.6.0 
Using a pure JS script, NodeJS v18.9.0.

**Comment by genixpro** [comment]
Unfortunately I'm not longer working for the company, so I can't help at
this point. But I can say the issue was reliably reproduced on our end, it
wasn't just a one off. We had to change our code to output strings instead
of integers and change the facets to strings in order to get the query to
work. I might be wrong in my assessment of what the underlying issue was,
but it was very reliably reproduced on our end.

**Comment by therve** [comment]
Finally managed to reproduce, thanks a lot for your reply.

**Comment by genixpro** [comment]
Amazing!  Good work.
------
Bradley Arsenault < ***@***.*** >
650-224-3734
Mountain View, California
